#!/usr/bin/env bash

timeout 30m python3 main.py "$@" -- \
    --metrics-root lean4cs1 \
    --exe-name build-doc \
    --project-url https://github.com/robsimmons/Lean4CS1.git \
    --project-branch verso \
    --project-dir lean4-cs1
