#!/usr/bin/env bash

# NB: refman already passes -O0, so we do not pass --opt.
timeout -s KILL 30m python3 main.py "$@" -- \
    --metrics-root refman \
    --exe-name generate-manual \
    --edit-file Manual/Tactics.lean \
    --project-url https://github.com/leanprover/reference-manual.git \
    --project-branch VERSO_LEAN_TOOLCHAIN \
    --project-dir refman \
    --exe-arg=--depth \
    --exe-arg=2 \
    --exe-arg=--delay-html-multi \
    --exe-arg=multi.json
