#!/usr/bin/env bash

timeout -s KILL 30m python3 main.py "$@" -- \
    --metrics-root lean4cs1-o0 \
    --exe-name build-doc \
    --edit-file FPCourse/Unit1/Week00_AlgebraicTypes.lean \
    --project-url https://github.com/robsimmons/Lean4CS1.git \
    --project-branch verso \
    --project-dir lean4-cs1 \
    --opt o0
