#!/usr/bin/env bash

python3 main.py "$@" -- \
    --metrics-root sherlock \
    --exe-name sherlock \
    --project-url https://github.com/robsimmons/sherlock-lean.git \
    --project-branch lean \
    --project-dir sherlock
