#!/usr/bin/env bash

timeout -s KILL 30m python3 main.py "$@" -- \
    --metrics-root blueprint-natson \
    --exe-name blueprint-gen \
    --project-url https://github.com/Vtec234/verso-natson.git \
    --project-branch main \
    --project-dir verso-natson \
    --pre-build-cmd ./scripts/pre-build.sh
