#!/usr/bin/env bash

timeout -s KILL 30m python3 main.py "$@" -- \
    --metrics-root sherlock-o0 \
    --exe-name sherlock \
    --project-url https://github.com/robsimmons/sherlock-lean.git \
    --project-branch lean \
    --project-dir sherlock \
    --opt o0
